name: cd
on:
  workflow_dispatch:
  check_run:
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Verify CI status
        uses: jenkins-infra/verify-ci-status-action@v1.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release Drafter
        uses: release-drafter/release-drafter@v5
        with:
          name: next
          tag: next
          version: next
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Interesting
        id: interesting
        run: |
          set -euxo pipefail
          echo $GITHUB_EVENT_NAME
          if [ "${GITHUB_EVENT_NAME}" = "push" ]
          then
            INTERESTING_CATEGORIES='[💥🚨🎉🐛⚠🚀👷]|:(boom|tada|construction_worker):'
            CATEGORIES=$(gh api /repos/$GITHUB_REPOSITORY/releases | jq -e -r '.[] | select(.draft == true and .name == "next") | .body')
            if echo "${CATEGORIES}" | egrep -q "${INTERESTING_CATEGORIES}"; then
              echo "Interesting release"
              echo "::set-output name=should_release::true"
            else
              echo "Not interesting release"
              echo "::set-output name=should_release::false"
            fi
          else
            echo "::set-output name=should_release::true"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: jenkins-infra/jenkins-maven-cd-action@v1.1.0
        if: steps.interesting.outputs.should_release == 'true'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
